### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by jojokester** [ircluzar/RTC#2] opened 2017-07-07 01:55 UTC
Every time I save a stockpile this error comes up.
I'm not very good with computers and have looked everywhere.
Help...

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at RTC.Stockpile.Save(Stockpile sks, Boolean IsQuickSave) in C:\Users\philt\Documents\PROJECTS\RTC\Dev BizHawk_RTC\BizHawk.Client.EmuHawk\RTC\RTC_Objects.cs:line 171
   at RTC.RTC_GH_Form.btnSaveStockpileAs_Click(Object sender, EventArgs e) in C:\Users\philt\Documents\PROJECTS\RTC\Dev BizHawk_RTC\BizHawk.Client.EmuHawk\RTC\RTC_GH_Form.cs:line 768
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by KingWormo** [comment] 2017-09-28 01:49
I had the same issue, until I caved and reset the settings, and now BizHawk and co. won't launch at all... The standalone counterpart does open according to the task manager though.

**Comment by ircluzar** [comment] 2017-09-28 03:20
I have encountered certain antivirus software that blocks the program due
to it's behavior (corrupting and stuff) being quite non-standard. The same
can happen with WGH and some anti-malware can even give a false positive,
thinking that it might be encrypting stuff, which it isn't.

Make sure you start the program using the batch files as they attempt to
kill the processes before starting them.
In case of doubt, you could try to temporary disable antivirus software or
delete RTC and reinstall it from scratch.

Please give us feedback on your issue.

**Comment by ircluzar** [comment] 2017-09-28 03:21
Also, about the savestate saving error, it might be caused by the use of non-standard characters. make sure you are not using characters like |$%?&+

**Comment by ircluzar** [comment] 2017-09-28 03:23
I will close this ticket as it is open in the old RTC Github. Please use the RTC3 repo for your issues. We are no longer developping pre 3.00

**Closed by ircluzar** 2017-09-28 03:23 UTC
